// Code generated by "stringer -type=Suit"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SPADE-0]
	_ = x[DIAMOND-1]
	_ = x[CLUB-2]
	_ = x[HEART-3]
	_ = x[JOKER-4]
}

const _Suit_name = "SPADEDIAMONDCLUBHEARTJOKER"

var _Suit_index = [...]uint8{0, 5, 12, 16, 21, 26}

func (i Suit) String() string {
	if i < 0 || i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
