// Code generated by "stringer -type=Type"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[ACE-1]
	_ = x[TWO-2]
	_ = x[THREE-3]
	_ = x[FOUR-4]
	_ = x[FIVE-5]
	_ = x[SIX-6]
	_ = x[SEVEN-7]
	_ = x[EIGHT-8]
	_ = x[NINE-9]
	_ = x[TEN-10]
	_ = x[JACK-11]
	_ = x[QUEEN-12]
	_ = x[KING-13]
}

const _Type_name = "NONEACETWOTHREEFOURFIVESIXSEVENEIGHTNINETENJACKQUEENKING"

var _Type_index = [...]uint8{0, 4, 7, 10, 15, 19, 23, 26, 31, 36, 40, 43, 47, 52, 56}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
